doctrine:
    dbal:
      dbname: '%env(resolve:APP_DATABASE_NAME)%'
      host: '%env(resolve:APP_DATABASE_HOST)%'
      port: '%env(resolve:APP_DATABASE_PORT)%'
      user: '%env(resolve:APP_DATABASE_USER)%'
      password: '%env(resolve:APP_DATABASE_SECRET)%'
      driver: '%env(resolve:APP_DATABASE_DRIVER)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
          Order:
            type: xml
            is_bundle: false
            dir: '%kernel.project_dir%/src/Order/src/Infrastructure/Persistence/Doctrine/Mapping'
            prefix: Order\Domain

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
